vim.cmd("command R terminal 'R'")
vim.cmd("command RScript tabe | terminal Rscript %")
vim.cmd("command LSession SessionManager load_session")
vim.cmd("command VR botright vsplit | terminal 'R'")
vim.cmd("command QuartoCheck tabe | terminal quarto check")
vim.cmd("command QuartoRender tabe %| terminal quarto render %")
vim.cmd("command QuartoRenderProject tabe %| terminal quarto render ./")
vim.cmd("command QuartoPreview  tabe %| terminal quarto preview ./")
vim.cmd("command ShowSpaceTable !column -s ' ' -t  < %")
vim.cmd("command ShowTabTable !column -s '\t' -t  < %")
vim.cmd("command ShowMarkDown !viewmd %")
vim.cmd("command GitHubPush !githubinit && git push")
vim.cmd("command RunApp tabe % | terminal R --slave -e \"shiny::runApp(launch.browser = TRUE)\"")
